FARBEN = [
    ("Violet", "#7c3aed"),
    ("Cyan", "#06b6d4"),
    ("Silber", "#c0c0c0"),
    ("Weiß", "#ffffff"),
    ("Lila", "#a855f7"),
    ("Pink", "#ec4899"),
    ("Grün", "#22c55e"),
    ("Blau", "#3b82f6"),
    ("Gelb", "#eab308"),
    ("Rot", "#ef4444"),
    ("Schwarz", "#000000"),
    ("Orange", "#f97316"),
    ("Türkis", "#2dd4bf"),
    ("Magenta", "#d946ef"),
    ("Gold", "#d4af37"),
    ("Bronze", "#cd7f32"),
    ("Beige", "#f5f5dc"),
    ("Anthrazit", "#293133"),
    ("Dunkelblau", "#1e3a8a"),
    ("Hellblau", "#7dd3fc"),
    ("Mint", "#98ff98"),
    ("Olive", "#808000"),
    ("Kupfer", "#b87333"),
    ("Perlmutt", "#eae0c8"),
    ("Champagner", "#f7e7ce"),
    ("Graphit", "#383838"),
    ("Neon Grün", "#39ff14"),
    ("Neon Pink", "#ff10f0"),
    ("Neon Blau", "#1f51ff"),
    ("Neon Orange", "#ff5f1f"),
    ("Matt Schwarz", "#1a1a1a"),
    ("Matt Grau", "#4b5563"),
    ("Matt Blau", "#1e3a8a"),
    ("Matt Rot", "#7f1d1d"),
    ("Metallic Blau", "#1e40af"),
    ("Metallic Rot", "#b91c1c"),
    ("Metallic Grün", "#166534"),
    ("Metallic Silber", "#9ca3af"),
    ("Ice White", "#f8fafc"),
    ("Royal Blue", "#4169e1"),
    ("Candy Red", "#ff003c"),
    ("Electric Purple", "#bf00ff"),
    ("Sunset Orange", "#ff4500"),
    ("Ocean Blue", "#006994"),
]

MARKEN = [
    "BMW",
    "Audi",
    "Mercedes",
    "Toyota",
    "Tesla",
    "Ferrari",
    "Lamborghini",
    "Porsche",
    "Ford",
    "VW",
    "Chevrolet",
    "Dodge",
    "Jeep",
    "Cadillac",
    "Buick",
    "Nissan",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Honda",
    "Hyundai",
    "Kia",
    "Peugeot",
    "Renault",
    "Citroën",
    "Skoda",
    "Seat",
    "Opel",
    "Fiat",
    "Mini",
    "Volvo",
    "Jaguar",
    "Land Rover",
    "Alfa Romeo",
    "Maserati",
    "Bentley",
    "Rolls Royce",
    "McLaren",
    "Bugatti",
    "Koenigsegg",
    "Pagani",
    "Rimac",
    "Lucid",
    "Polestar",
    "BYD",
    "Geely",
    "Great Wall",
    "Chery",
    "Daihatsu",
    "Suzuki",
    "Aston Martin",
    "Lotus",
    "Lexus",
    "Infiniti",
    "Genesis",
    "Cupra",
    "Smart",
    "Hummer",
    "Rivian",
    "Scania",
]

PREMIUM_MARKEN = [
    "Aston Martin",
    "Bentley",
    "Bugatti",
    "Ferrari",
    "Koenigsegg",
    "Lamborghini",
    "Lotus",
    "Lucid",
    "Maserati",
    "McLaren",
    "Pagani",
    "Porsche",
    "Rimac",
    "Rolls Royce",
    "Tesla",
]

BESITZER = [
    "Renz",
    "Alex",
    "Mika",
    "Sam",
    "Jules",
    "Noa",
    "Chris",
    "Taylor",
    "Kim",
    "Niko",
    "Sami",
    "Robin",
]

AUTOHAUS = [
    "Autohaus Schneider",
    "Autohaus Müller",
    "Autozentrum Becker",
    "KFZ Zentrum Hoffmann",
    "Autohaus König",
    "Fahrzeughandel Wagner",
    "Autohaus Richter",
    "Mobilzentrum Weber",
    "Autohaus Schäfer",
    "KFZ Zentrum Bauer",
]

PREMIUM_AUTOHAUS = [
    "Imperial Motors",
    "Royal Drive Autohaus",
    "Prestige Automotive",
    "Elite Car Lounge",
    "Diamond Motors",
    "Velvet Wheels",
    "Prime Auto Group",
    "Luxury Ride Center",
    "Signature Motors",
    "Platinum Autohaus",
]

ALLE_AUTOHAEUSER = AUTOHAUS + PREMIUM_AUTOHAUS

Autos = []
